export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const FETCH_FEED_ITEMS = "FETCH_FEED_ITEMS";
export const FETCH_FAVOURITE_ITEMS = "FETCH_FAVOURITE_ITEMS";
export const FETCH_MY_LISTINGS = "FETCH_MY_LISTINGS";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
